version: '3.7'

#
# To use this one should use a LB proxy in front to access from the internet.
# I use haproxy which temrinates the SSL. Ex: haproxy.cfg included in this repo.
#

services:
  db:
    # image: linuxserver/mariadb
    image: mariadb
    restart: always
    volumes:
      # - /var/piwigo/config:/config
      - /var/piwigo/mysql:/var/lib/mysql
    environment:
      # I don't know if mariadb actually uses TZ.
      TZ: "US/Eastern"
      # This is only used in initialization (first bringup) of the DB
      MYSQL_DATABASE: piwigodb
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: "ChangeToAPasswordForUser_piwigo"
      # XXX I couldn't get secrets to work.
      # MYSQL_PASSWORD_FILE: /run/secrets/piwigouser
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    # secrets:
    #   - piwigouser
    networks:
      piwigo:
        ipv4_address: 10.1.0.3

  piwigo:
    # image: linuxserver/piwigo
    image: choppsv1/piwigo
    build:
      context: "."
      dockerfile: Dockerfile
    restart: always
    environment:
      # This is my (chopps) UID
      PUID: "10001"
      # This is my "users" GID
      PGID: "2000"
      TZ: "US/Eastern"
    networks:
      piwigo:
        ipv4_address: 10.1.0.2
    ports:
      - "8081:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - /var/piwigo/config:/config
      - /var/piwigo/gallery:/config/www/gallery
#     - PIWIGO_DATA:/var/www/_data/i
#     - PIWIGO_GALLERIES:/var/www/galleries
#     - PIWIGO_UPLOAD:/var/www/upload

networks:
  piwigo:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24

# secrets:
#   piwigouser:
#     file: /var/piwigo/deploy/secrets/piwigouser
